### ISSUE TITLE
Grindhead/1.21/Forge

### ISSUE THREAD

**Issue by TheNightfuel** [x-j0nnay-x/Simpel-Adds#10]
Unsure if this is an issue or not but are the grindheads suppose to be consumed in the crafting table? I thought it consumed durability rather than the whole thing.

**Comment by x-j0nnay-x** [comment]
This is Fixed in V1.116 of the mod. But the Dooping Glitch is back, as minecraft repair items does not have a check that will allow me to negate it. so sad.
