### ISSUE TITLE
fix your spelling on everything

### ISSUE THREAD

**Issue by wolfieboy09** [x-j0nnay-x/Simpel-Adds#11]
`simpel` -> `simple` (correct spelling)

don't make me make a pr on your entire README.md, and PLEASE use branches for different Minecraft versions

**Comment by x-j0nnay-x** [comment]
working on it, hey i'm not the best speller my guy. brain don't spell good lol. but will work on it. and the naming is on prepose that is how i wanted it to be spelt my guy.
