### ISSUE TITLE
Unable to load in 1.20.1-Fabric 0.15.11 version

### ISSUE THREAD

**Issue by LuckyDog322** [x-j0nnay-x/Simpel-Adds#2]
There is already a mod in the folder, but it is not running in the game
![屏幕截图 2024-07-03 170157](https://github.com/x-j0nnay-x/Simpel-Adds/assets/137597710/f78cd33d-804c-4977-afd1-bdc4eb958cd6)

**Comment by x-j0nnay-x** [comment]
That's because i don't have a fabric version of the mod for 1.20.1 I have one for 1.20.2. this is something I am currently working on. wile Im updating to the MultiLoader format

**Comment by x-j0nnay-x** [comment]
Just Uploaded the 1.20.1 Fabric version if you still want it

**Comment by LuckyDog322** [comment]
> 如果你还想要的话，刚刚上传了 1.20.1 Fabric 版本

Wow! This is really wonderful, thank you for your efforts.
