### ISSUE TITLE
It crashes when you use grinderhead to make iron dust

### ISSUE THREAD

**Issue by LuckyDog322** [x-j0nnay-x/Simpel-Adds#3]
[crash-2024-07-15_15.13.34-client.txt](https://github.com/user-attachments/files/16231096/crash-2024-07-15_15.13.34-client.txt)
version：1.20.1 fabric
version：SimpelAdd-fabric-1.20.1-1.109

**Comment by x-j0nnay-x** [comment]
This is now Fixed in Version 1.110. Thank you For the Bug Report.

**Comment by LuckyDog322** [comment]
ok
