### ISSUE TITLE
Recipe

### ISSUE THREAD

**Issue by TheNightfuel** [x-j0nnay-x/Simpel-Adds#4]
Unsure if I'm doing something wrong or loaded the mod incorrectly but I'm having trouble finding the recipe for the grinder head? Or any description on where I can find the item. 

Version 1.21 
Forge

**Comment by x-j0nnay-x** [comment]
This happened since minecraft now wont let you craft items that cant stack. so you used to get two grind heads but i just fixed this. V1.111 will be relaced here in a few moments, go ahead and download it one you get it. thank you for the bug report.

**Comment by x-j0nnay-x** [comment]
The new version is out. 

Thanks again
