### ISSUE TITLE
infinite grinderhead

### ISSUE THREAD

**Issue by LuckyDog322** [x-j0nnay-x/Simpel-Adds#5]
version:1.20.1 fabric
version:1.110
Two grinding heads can make unlimited grinding heads
![2024-07-18_12 37 12](https://github.com/user-attachments/assets/57c433d2-8450-4e3d-acfb-42e8bdf4333e)

**Comment by x-j0nnay-x** [comment]
WOW that is Funny, vanilla has that built in, I over looked that, now putting out a fix.  this is truly funny. thank you for the Bug report.

V1.112 is out now

**Comment by LuckyDog322** [comment]
ok
