### ISSUE TITLE
Diamonds/Emerald Ore/1.21/Forge

### ISSUE THREAD

**Issue by TheNightfuel** [x-j0nnay-x/Simpel-Adds#7]
The diamond ore block and the emerald ore block doesn't work in the grinder? Or is that intended?

**Comment by x-j0nnay-x** [comment]
This is intended as I do not have any dusts for them. And just have not thought they should double, or not

**Comment by x-j0nnay-x** [comment]
in version 1.113 you will be able to triple Diamond, Emerald, Coal ore, both manually and in the grinder
