### ISSUE TITLE
Lava Bucket as Fuel/Forge/1.21

### ISSUE THREAD

**Issue by TheNightfuel** [x-j0nnay-x/Simpel-Adds#8]
So, apparently, when adding a lava bucket into the upgraded furnace, it completely crashes the game. Null Error. I tested it in creative, and it happens every time. Unfortunately, I lost one of my good worlds as a result to the discovery of the bug.

**Comment by x-j0nnay-x** [comment]
V1.114 will be up soon with a fix for this, your world should be retrievable
