### ISSUE TITLE
Grinder Recipe/Forge/1.21

### ISSUE THREAD

**Issue by TheNightfuel** [x-j0nnay-x/Simpel-Adds#9]
The newest version has a bug related to the grinder block, not showing up in the recipe book nor with JEI.  Unsure if thats a bug with JEI or this mod, but its also not showing up for the the vanilla recipe book

**Comment by x-j0nnay-x** [comment]
I Really dont know about the recipe book thing as crafting is all vanilla, JEI should show all recipes.

**Comment by TheNightfuel** [comment]
> I Really dont know about the recipe book thing as crafting is all vanilla, JEI should show all recipes.

Yeah, I'm still unable to craft neither grinders, normal or netherite

**Comment by x-j0nnay-x** [comment]
Im so dumb -,- i did not change there name to crafting_ so i thought they where grindering recipes -,- need to change item to ID, ill reupload fix

**Comment by x-j0nnay-x** [comment]
they are uploaded, should be live soon, thank you again for your bug report and help.
